//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace p2.ServicioFintech {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMovtosOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertMovtosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitudDeloginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDeSaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransferenciaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://wcf1nt3ch2018.azurewebsites.net/Service1.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMovtosCompletedEventHandler GetMovtosCompleted;
        
        /// <remarks/>
        public event InsertMovtosCompletedEventHandler InsertMovtosCompleted;
        
        /// <remarks/>
        public event CrearSessionCompletedEventHandler CrearSessionCompleted;
        
        /// <remarks/>
        public event SolicitudDeloginCompletedEventHandler SolicitudDeloginCompleted;
        
        /// <remarks/>
        public event ConsultaDeSaldoCompletedEventHandler ConsultaDeSaldoCompleted;
        
        /// <remarks/>
        public event TransferenciaCompletedEventHandler TransferenciaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetMovtos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CardlessWcf")]
        public Movto[] GetMovtos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CutomerName) {
            object[] results = this.Invoke("GetMovtos", new object[] {
                        CutomerName});
            return ((Movto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMovtosAsync(string CutomerName) {
            this.GetMovtosAsync(CutomerName, null);
        }
        
        /// <remarks/>
        public void GetMovtosAsync(string CutomerName, object userState) {
            if ((this.GetMovtosOperationCompleted == null)) {
                this.GetMovtosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMovtosOperationCompleted);
            }
            this.InvokeAsync("GetMovtos", new object[] {
                        CutomerName}, this.GetMovtosOperationCompleted, userState);
        }
        
        private void OnGetMovtosOperationCompleted(object arg) {
            if ((this.GetMovtosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMovtosCompleted(this, new GetMovtosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertMovtos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertMovtos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Movto customerInfo) {
            object[] results = this.Invoke("InsertMovtos", new object[] {
                        customerInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertMovtosAsync(Movto customerInfo) {
            this.InsertMovtosAsync(customerInfo, null);
        }
        
        /// <remarks/>
        public void InsertMovtosAsync(Movto customerInfo, object userState) {
            if ((this.InsertMovtosOperationCompleted == null)) {
                this.InsertMovtosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMovtosOperationCompleted);
            }
            this.InvokeAsync("InsertMovtos", new object[] {
                        customerInfo}, this.InsertMovtosOperationCompleted, userState);
        }
        
        private void OnInsertMovtosOperationCompleted(object arg) {
            if ((this.InsertMovtosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMovtosCompleted(this, new InsertMovtosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CrearSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CrearSession() {
            object[] results = this.Invoke("CrearSession", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearSessionAsync() {
            this.CrearSessionAsync(null);
        }
        
        /// <remarks/>
        public void CrearSessionAsync(object userState) {
            if ((this.CrearSessionOperationCompleted == null)) {
                this.CrearSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearSessionOperationCompleted);
            }
            this.InvokeAsync("CrearSession", new object[0], this.CrearSessionOperationCompleted, userState);
        }
        
        private void OnCrearSessionOperationCompleted(object arg) {
            if ((this.CrearSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearSessionCompleted(this, new CrearSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SolicitudDelogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SolicitudDelogin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Token) {
            object[] results = this.Invoke("SolicitudDelogin", new object[] {
                        Token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitudDeloginAsync(string Token) {
            this.SolicitudDeloginAsync(Token, null);
        }
        
        /// <remarks/>
        public void SolicitudDeloginAsync(string Token, object userState) {
            if ((this.SolicitudDeloginOperationCompleted == null)) {
                this.SolicitudDeloginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitudDeloginOperationCompleted);
            }
            this.InvokeAsync("SolicitudDelogin", new object[] {
                        Token}, this.SolicitudDeloginOperationCompleted, userState);
        }
        
        private void OnSolicitudDeloginOperationCompleted(object arg) {
            if ((this.SolicitudDeloginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitudDeloginCompleted(this, new SolicitudDeloginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultaDeSaldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaDeSaldo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Token, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string numCuenta) {
            object[] results = this.Invoke("ConsultaDeSaldo", new object[] {
                        Token,
                        numCuenta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDeSaldoAsync(string Token, string numCuenta) {
            this.ConsultaDeSaldoAsync(Token, numCuenta, null);
        }
        
        /// <remarks/>
        public void ConsultaDeSaldoAsync(string Token, string numCuenta, object userState) {
            if ((this.ConsultaDeSaldoOperationCompleted == null)) {
                this.ConsultaDeSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDeSaldoOperationCompleted);
            }
            this.InvokeAsync("ConsultaDeSaldo", new object[] {
                        Token,
                        numCuenta}, this.ConsultaDeSaldoOperationCompleted, userState);
        }
        
        private void OnConsultaDeSaldoOperationCompleted(object arg) {
            if ((this.ConsultaDeSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDeSaldoCompleted(this, new ConsultaDeSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Transferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Transferencia([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Token, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string numCuentaDeRetiro, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumCuentaDeDeposito, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Motivo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Monto) {
            object[] results = this.Invoke("Transferencia", new object[] {
                        Token,
                        numCuentaDeRetiro,
                        NumCuentaDeDeposito,
                        Motivo,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TransferenciaAsync(string Token, string numCuentaDeRetiro, string NumCuentaDeDeposito, string Motivo, string Monto) {
            this.TransferenciaAsync(Token, numCuentaDeRetiro, NumCuentaDeDeposito, Motivo, Monto, null);
        }
        
        /// <remarks/>
        public void TransferenciaAsync(string Token, string numCuentaDeRetiro, string NumCuentaDeDeposito, string Motivo, string Monto, object userState) {
            if ((this.TransferenciaOperationCompleted == null)) {
                this.TransferenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransferenciaOperationCompleted);
            }
            this.InvokeAsync("Transferencia", new object[] {
                        Token,
                        numCuentaDeRetiro,
                        NumCuentaDeDeposito,
                        Motivo,
                        Monto}, this.TransferenciaOperationCompleted, userState);
        }
        
        private void OnTransferenciaOperationCompleted(object arg) {
            if ((this.TransferenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransferenciaCompleted(this, new TransferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CardlessWcf")]
    public partial class Movto {
        
        private string bancoField;
        
        private string cuentaField;
        
        private decimal montoField;
        
        private bool montoFieldSpecified;
        
        private string nombreField;
        
        private string respuestaField;
        
        private string usuarioField;
        
        private string codigoCobroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoCobro {
            get {
                return this.codigoCobroField;
            }
            set {
                this.codigoCobroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetMovtosCompletedEventHandler(object sender, GetMovtosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMovtosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMovtosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertMovtosCompletedEventHandler(object sender, InsertMovtosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertMovtosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertMovtosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CrearSessionCompletedEventHandler(object sender, CrearSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SolicitudDeloginCompletedEventHandler(object sender, SolicitudDeloginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitudDeloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitudDeloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ConsultaDeSaldoCompletedEventHandler(object sender, ConsultaDeSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDeSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDeSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TransferenciaCompletedEventHandler(object sender, TransferenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransferenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591